// Using array join to avoid template literal escaping issues
export const PROXY_REQUEST_TEMPLATE = [
  "import type { NextRequest } from 'next/server';",
  "",
  "function rewriteUrl({",
  "  requestUrl,",
  "  replacePath,",
  "}: {",
  "  requestUrl: string;",
  "  replacePath?: string;",
  "}) {",
  "  const API_BASE_URL = process.env.API_BASE_URL;",
  "  const tobeReplacedPath =",
  "    replacePath ?? requestUrl.replace(/^https?:\\/\\/[^\\/]+(:d+)?\\/api\\//, '');",
  "",
  "  return `${API_BASE_URL}/${tobeReplacedPath}`;",
  "}",
  "",
  "export const proxyRequest = async ({",
  "  req,",
  "  path,",
  "}: {",
  "  req: NextRequest;",
  "  path?: string;",
  "}): Promise<Response> => {",
  "  let body: string | undefined = undefined;",
  "  try {",
  "    body = JSON.stringify(await req.json());",
  "  } catch (err) {}",
  "",
  "  const reqHeaders: Record<string, string> = {};",
  "  req.headers.forEach((value, key) => {",
  "    if (['content-length'].includes(key)) return;",
  "    reqHeaders[key] = value;",
  "  });",
  "",
  "  const resp = await fetch(",
  "    rewriteUrl({ requestUrl: req.url, replacePath: path }),",
  "    {",
  "      method: req.method,",
  "      body,",
  "      headers: {",
  "        ...reqHeaders,",
  "        'x-api-key': 'secret1',",
  "      },",
  "      cache: 'no-store',",
  "    },",
  "  );",
  "",
  "  return resp;",
  "};",
  "",
].join("\n");
