import type { SQSBatchItemFailure, SQSEvent } from 'aws-lambda';
import { DependencyContainer } from 'monorise/core';

// Import config — this will be generated by monorise CLI
let config: any;
try {
  config = require('../../.monorise/config');
} catch {
  // Fallback for when .monorise hasn't been generated yet
  config = { EntityConfig: {}, AllowedEntityTypes: [], EmailAuthEnabledEntities: [] };
}

const container = new DependencyContainer(config);

type EventDetail = {
  entityType: string;
  entityId: string;
  data: {
    amount?: number;
    type?: 'sale' | 'refund' | 'discount';
    transactionDate?: string;
    merchantId?: string;
    buyerId?: string;
    [key: string]: any;
  };
};

export const handler = async (event: SQSEvent) => {
  const batchItemFailures: SQSBatchItemFailure[] = [];

  for (const record of event.Records) {
    try {
      const body = JSON.parse(record.body);
      const detail: EventDetail = body.detail;

      // Only process transaction entities
      if (detail.entityType !== 'transaction') continue;

      const { merchantId, amount, type, transactionDate } = detail.data;
      if (!merchantId || !amount || !type || !transactionDate) continue;

      const month = transactionDate.slice(0, 7); // YYYY-MM
      const summaryId = `${merchantId}-${month}`;

      // Calculate deltas based on transaction type
      const totalSales = type === 'sale' ? amount : 0;
      const totalRefunds = type === 'refund' ? amount : 0;
      const totalDiscounts = type === 'discount' ? amount : 0;
      const netTotal = totalSales - totalRefunds - totalDiscounts;

      // Try to adjust existing summary
      try {
        await container.entityService.adjustEntity({
          entityType: 'monthly-summary' as any,
          entityId: summaryId,
          adjustments: {
            totalSales,
            totalRefunds,
            totalDiscounts,
            netTotal,
            count: 1,
          },
        });
      } catch (err: any) {
        // If entity doesn't exist, create it first
        if (err?.code === 'ENTITY_IS_UNDEFINED' || err?.message?.includes('Entity item empty')) {
          await container.entityService.createEntity({
            entityType: 'monthly-summary' as any,
            entityPayload: {
              merchantId,
              month,
              totalSales,
              totalRefunds,
              totalDiscounts,
              netTotal,
              count: 1,
              merchantIds: [merchantId],
            },
            entityId: summaryId,
          });
        } else {
          throw err;
        }
      }

      console.log(`Updated monthly summary ${summaryId}: +${amount} (${type})`);
    } catch (err) {
      console.error('Summary processor error:', err);
      batchItemFailures.push({ itemIdentifier: record.messageId });
    }
  }

  return { batchItemFailures };
};
