/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "API_KEYS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Web": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "core-core-replicator-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "core-core-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "core-monorise-api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "core-monorise-bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "core-monorise-dlq-alarm-topic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "mutual-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "mutual-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "mutual-queue-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "summary-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "summary-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "summary-queue-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tag-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "tag-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tag-queue-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tree-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "tree-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tree-queue-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}