name: Build

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  # lint:
  #   name: Run Linter
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Run linter
  #       run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    # needs: lint
    services:
      localstack:
        image: localstack/localstack:4.3.0
        ports:
          - 4566:4566
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run test for @monorise/core
        run: npm run test
        env:
          LOCALSTACK_ENDPOINT: http://localhost:4566

  build:
    name: Build Package
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: |
          npm run build
          chmod +x packages/cli/dist/cli.js
