/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "API_KEYS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "app-core-replicator-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "app-core-table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "app-monorise-api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "app-monorise-bus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "app-monorise-dlq-alarm-topic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "app-websocket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "app-ws-connect": {
      "name": string
      "type": "sst.aws.Function"
    }
    "app-ws-default": {
      "name": string
      "type": "sst.aws.Function"
    }
    "app-ws-disconnect": {
      "name": string
      "type": "sst.aws.Function"
    }
    "chat-ui": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "mutual-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "mutual-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "mutual-queue-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tag-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "tag-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tag-queue-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tree-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "tree-queue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "tree-queue-dlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}